-- Deploy catmash:firstmigra to pg

BEGIN;

-- XXX Add DDLs here.
CREATE TABLE "cat" (
  "id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "image_path" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);

CREATE TABLE "vote" (
  "id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "cat_id" INT NOT NULL REFERENCES "cat"("id"),
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP
);




COMMIT;
